darkweb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, re_path
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    re_path(r'^media/(?P<path>.*)$', serve,
            {'document_root': settings.MEDIA_ROOT}),

    re_path(r'^static/(?P<path>.*)$', serve,
            {'document_root': settings.STATIC_ROOT}),
]


# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from .views import *
import random
app_name = 'amydo'

urlpatterns = [
    path('', IndexView.as_view(), name='index' ),
    path('product/<str:slug>', ProductDetailView.as_view(), name='product_detail'),
    path('cart', CartView.as_view(), name='my-cart'),
    path('checkout', CheckOutView.as_view(), name='checkout'),
    path('category/<str:slug>', CategoryView.as_view(), name='category'),
]

main/models.py
from distutils.command.upload import upload
from statistics import mode
from unicodedata import category
from django.db import models
from django.contrib.auth.models import User
from django.utils.timezone import now
from autoslug import AutoSlugField
# Create your models here.

class Category(models.Model):
    title = models.CharField(max_length=200)
    image = models.ImageField(upload_to = 'cat_img', null = True, blank = True)
    slug =  AutoSlugField(populate_from='title', editable = True)

    def __str__(self):
        return self.title

class SubCategory(models.Model):
	category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)
	title = models.CharField(max_length=200)
	slug = AutoSlugField(populate_from='title')

	def __str__(self):
		return self.title

class Product(models.Model):
	name = models.CharField(max_length=200, null =True, blank = True)
	category =models.ForeignKey(Category, on_delete=models.CASCADE)
	subcategory =models.ForeignKey(SubCategory, on_delete=models.CASCADE)
	image = models.FileField(upload_to='products/')
	slug =  AutoSlugField(populate_from='name')
	def __str__(self):
		return self.name

class ProductImage(models.Model):
	product = models.ForeignKey(Product, on_delete=models.CASCADE)
	image = models.ImageField(upload_to='products.image/')

	def __str__(self):
		return self.product.name
	

class Review(models.Model):
    review = models.TextField()
    name = models.CharField(max_length = 56)

main/views.py
from itertools import product
from django.shortcuts import render
from django.views.generic import (CreateView, DetailView, FormView, ListView,
                                  TemplateView, View)
from .models import *
# Create your views here.

class IndexView(TemplateView):
    template_name = 'main/index.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        products = Product.objects.filter(category__title = 'Drugs') 
        category = Category.objects.all()
        context["products"] = products
        context['category'] = category
        return context

class CartView(TemplateView):
	template_name = 'main/cart.html'

class ProductDetailView(DetailView):
    template_name = 'main/product_detail.html'
    model = Product
    context_object_name = 'product'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        slug = self.kwargs['slug']
        p = Product.objects.get(slug = slug)
        cat = p.category
        products = Product.objects.filter(category = cat)
        context["products"] = products
        return context
        
class CategoryView(TemplateView):
    template_name = 'main/category.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        slug = kwargs['slug']
        products = Product.objects.filter(category__slug = slug)
        context["products"] = products
        return context
    

class CheckOutView(TemplateView):
	template_name = 'main/checkout.html'

class SideBar(View):
    template_name = 'sidebar.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["category"] = Category.objects.all() 
        return context
    

templates/base.html
{% load cache %}
{% load static %}
{% load i18n %}
{% load humanize %}
<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>
		{% block title %}
		  
		{% endblock title %}
	</title>
	<meta name="description" content="">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="robots" content="all,follow">
	<!-- gLightbox gallery-->
	<link rel="stylesheet" href="{% static 'vendor/glightbox/css/glightbox.min.css' %}">
	<!-- Range slider-->
	<link rel="stylesheet" href="{% static 'vendor/nouislider/nouislider.min.css' %}">
	<!-- Choices CSS-->
	<link rel="stylesheet" href="{% static 'vendor/choices.js/public/assets/styles/choices.min.css' %}">
	<!-- Swiper slider-->
	<link rel="stylesheet" href="{% static 'vendor/swiper/swiper-bundle.min.css' %}">
	<!-- Google fonts-->
	<link rel="stylesheet"
		href="https://fonts.googleapis.com/css2?family=Libre+Franklin:wght@300;400;700&amp;display=swap">
	<link rel="stylesheet"
		href="https://fonts.googleapis.com/css2?family=Martel+Sans:wght@300;400;800&amp;display=swap">
	
	<!-- theme stylesheet-->
	<link rel="stylesheet" href="{% static 'css/style.default.css' %}" id="theme-stylesheet">
	<!-- Custom stylesheet - for your changes-->
	<link rel="stylesheet" href="{% static 'css/custom.css' %}">
	<!-- Favicon-->
	<link rel="shortcut icon" href="{% static 'img/favicon.png' %}">

	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.1/css/all.css">
</head>
<style>
.float{
	position:fixed;
	width:60px;
	height:60px;
	bottom:40px;
	right:40px;
	background-color:#25d366;
	color:#FFF;
	border-radius:50px;
	text-align:center;
  font-size:30px;
	box-shadow: 2px 2px 3px #999;
  z-index:100;
}

.my-float{
	margin-top:16px;
}
</style>

<body>
	<div class="page-holder">
		<!-- navbar -->
		<header class="header bg-white">
			<div class="container px-lg-3">
				<nav class="navbar navbar-expand-lg navbar-light py-3 px-lg-0"><a class="navbar-brand" href="{% url 'amydo:index' %}"><span
							class="fw-bold text-uppercase text-dark">SHARJA PHARMA</span></a>
					<button class="navbar-toggler navbar-toggler-end" type="button" data-bs-toggle="collapse"
						data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
						aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
					<div class="collapse navbar-collapse" id="navbarSupportedContent">
						<ul class="navbar-nav me-auto">
							<li class="nav-item">
								<!-- Link--><a class="nav-link active" href="{% url 'amydo:index' %}">Home</a>
							</li>
							<li class="nav-item">
								<!-- Link--><a class="nav-link" href="">About Us</a>
							</li>
							<li class="nav-item">
								<!-- Link--><a class="nav-link" href="">Why US</a>
							</li>
							<li class="nav-item">
								<!-- Link--><a class="nav-link" href="">Contact US</a>
							</li>
							<li class="nav-item">
								<!-- Link--><a class="nav-link" href="">Pay Directly</a>
							</li>
							
						</ul>
					</div>
				</nav>
			</div>
			<nav class="navbar navbar-light px-lg-5">
				<div>
					<ul class="navbar-nav me-auto">
						<li class="nav-item">
							<!-- Link--><a class="nav-link" href="">Wickr id: mariam1988h</a>
						</li>
							
					</ul>
				</div>
			</nav>
		</header>
			<!--  Modal -->


			{% block content %}
		  
		{% endblock content %}	
	
		

<a href="https://api.whatsapp.com/send?phone=00971552055696&text=hey,%20I%20want%20_________." class="float" target="_blank">
<i class="fab fa-whatsapp my-float">
	
</i>
</a>
	</div>
	
	<!-- ======= Footer ======= -->
	<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
	<script src="{% static 'main.js' %}"></script>

	<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
	<!-- JavaScript files-->
	<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
	<script src="{% static 'vendor/glightbox/js/glightbox.min.js' %}"></script>
	<script src="{% static 'vendor/nouislider/nouislider.min.js' %}"></script>
	<script src="{% static 'vendor/swiper/swiper-bundle.min.js' %}"></script>
	<script src="{% static 'vendor/choices.js/public/assets/scripts/choices.min.js' %}"></script>
	<script src="{% static 'js/front.js' %}"></script>
	<script>

		function injectSvgSprite(path) {

			var ajax = new XMLHttpRequest();
			ajax.open("GET", path, true);
			ajax.send();
			ajax.onload = function (e) {
				var div = document.createElement("div");
				div.className = 'd-none';
				div.innerHTML = ajax.responseText;
				document.body.insertBefore(div, document.body.childNodes[0]);
			}
		}
		injectSvgSprite('https://bootstraptemple.com/files/icons/orion-svg-sprite.svg');

	</script>
	<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
	<!-- FontAwesome CSS - loading as last, so it doesn't block rendering-->
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css"
		integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
		

</body>
</html>

templates/main/add_product.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
add product
{% endblock title %}
{% block content %}
<div class="row p-sm-5 m-md-3 justify-content-center py-5">
    <div class="col col-lg-6 border-0">
        {% if error %}
        <div class="alert alert-danger" role="alert">
            <strong>{{error}}</strong>
        </div>
        {% endif %}
        <div class="card rounded-5 border-0" style="width: 100%">
            <div class="card-title ml-3">
                <span>
                    <p>
                        <span class="font-weight-bold h3">Sell Your Product</span> <br />
                        It's quick and easy
                    </p>
                </span>
            </div>
            <hr />
            <div class="card-body p-sm-2 mt-2">
                <form action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{form.media.js}}
                    {{form|crispy}}
                    <button class="btn btn-info">Upload Product</button>
                </form>

            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/main/cart.html
{% extends 'base.html' %}
{% load humanize %}    
{% load static %}
{% block title %}Welcome to AMYDO-MARKET
{% endblock title %} 
{% block content %}
<div class="container">
        <!-- HERO SECTION-->
        <section class="py-5 bg-light">
          <div class="container">
            <div class="row px-4 px-lg-5 py-lg-4 align-items-center">
              <div class="col-lg-6">
                <h1 class="h2 text-uppercase mb-0">Cart</h1>
              </div>
              <div class="col-lg-6 text-lg-end">
                <nav aria-label="breadcrumb">
                  <ol class="breadcrumb justify-content-lg-end mb-0 px-0 bg-light">
                    <li class="breadcrumb-item"><a class="text-dark" href="{% url 'amydo:index' %}">Home</a></li>
                    <li class="breadcrumb-item active" aria-current="page">Cart</li>
                  </ol>
                </nav>
              </div>
            </div>
          </div>
        </section>
        <section class="py-5">
          <h2 class="h5 text-uppercase mb-4">Shopping cart</h2>
          <div class="row">
            <div class="col-lg-8 mb-4 mb-lg-0">
              <!-- CART TABLE-->
              <div class="table-responsive mb-4">
                <table class="table text-nowrap">
                  <thead class="bg-light">
                    <tr>
                      <th class="border-0 p-3" scope="col"> <strong class="text-sm text-uppercase">Product</strong></th>
                      <th class="border-0 p-3" scope="col"> <strong class="text-sm text-uppercase">Price</strong></th>
                      <th class="border-0 p-3" scope="col"> <strong class="text-sm text-uppercase">Quantity</strong></th>
                      <th class="border-0 p-3" scope="col"> <strong class="text-sm text-uppercase">Total</strong></th>
                      <th class="border-0 p-3" scope="col"> <strong class="text-sm text-uppercase"></strong></th>
                    </tr>
                  </thead>
                  <tbody class="border-0">
                    <tr>
                      <th class="ps-0 py-3 border-light" scope="row">
                        <div class="d-flex align-items-center"><a class="reset-anchor d-block animsition-link" href="{% url 'amydo:product_detail' %}"><img src="{% static 'img//product-detail-3.jpg' %}" alt="..." width="70"/></a>
                          <div class="ms-3"><strong class="h6"><a class="reset-anchor animsition-link" href="{% url 'amydo:product_detail' %}">Red digital smartwatch</a></strong></div>
                        </div>
                      </th>
                      <td class="p-3 align-middle border-light">
                        <p class="mb-0 small">$250</p>
                      </td>
                      <td class="p-3 align-middle border-light">
                        <div class="border d-flex align-items-center justify-content-between px-3"><span class="small text-uppercase text-gray headings-font-family">Quantity</span>
                          <div class="quantity">
                            <button class="dec-btn p-0"><i class="fas fa-caret-left"></i></button>
                            <input class="form-control form-control-sm border-0 shadow-0 p-0" type="text" value="1"/>
                            <button class="inc-btn p-0"><i class="fas fa-caret-right"></i></button>
                          </div>
                        </div>
                      </td>
                      <td class="p-3 align-middle border-light">
                        <p class="mb-0 small">$250</p>
                      </td>
                      <td class="p-3 align-middle border-light"><a class="reset-anchor" href="#!"><i class="fas fa-trash-alt small text-muted"></i></a></td>
                    </tr>
                    <tr>
                      <th class="ps-0 py-3 border-0" scope="row">
                        <div class="d-flex align-items-center"><a class="reset-anchor d-block animsition-link" href="{% url 'amydo:product_detail' %}"><img src="{% static 'img//product-detail-2.jpg' %}" alt="..." width="70"/></a>
                          <div class="ms-3"><strong class="h6"><a class="reset-anchor animsition-link" href="{% url 'amydo:product_detail' %}">Apple watch</a></strong></div>
                        </div>
                      </th>
                      <td class="p-3 align-middle border-0">
                        <p class="mb-0 small">$250</p>
                      </td>
                      <td class="p-3 align-middle border-0">
                        <div class="border d-flex align-items-center justify-content-between px-3"><span class="small text-uppercase text-gray headings-font-family">Quantity</span>
                          <div class="quantity">
                            <button class="dec-btn p-0"><i class="fas fa-caret-left"></i></button>
                            <input class="form-control form-control-sm border-0 shadow-0 p-0" type="text" value="1"/>
                            <button class="inc-btn p-0"><i class="fas fa-caret-right"></i></button>
                          </div>
                        </div>
                      </td>
                      <td class="p-3 align-middle border-0">
                        <p class="mb-0 small">$250</p>
                      </td>
                      <td class="p-3 align-middle border-0"><a class="reset-anchor" href="#!"><i class="fas fa-trash-alt small text-muted"></i></a></td>
                    </tr>
                  </tbody>
                </table>
              </div>
              <!-- CART NAV-->
              <div class="bg-light px-4 py-3">
                <div class="row align-items-center text-center">
                  <div class="col-md-6 mb-3 mb-md-0 text-md-start"><a class="btn btn-link p-0 text-dark btn-sm" href="shop.html"><i class="fas fa-long-arrow-alt-left me-2"> </i>Continue shopping</a></div>
                  <div class="col-md-6 text-md-end"><a class="btn btn-outline-dark btn-sm" href="{% url 'amydo:checkout' %}">Procceed to checkout<i class="fas fa-long-arrow-alt-right ms-2"></i></a></div>
                </div>
              </div>
            </div>
            <!-- ORDER TOTAL-->
            <div class="col-lg-4">
              <div class="card border-0 rounded-0 p-lg-4 bg-light">
                <div class="card-body">
                  <h5 class="text-uppercase mb-4">Cart total</h5>
                  <ul class="list-unstyled mb-0">
                    <li class="d-flex align-items-center justify-content-between"><strong class="text-uppercase small font-weight-bold">Subtotal</strong><span class="text-muted small">$250</span></li>
                    <li class="border-bottom my-2"></li>
                    <li class="d-flex align-items-center justify-content-between mb-4"><strong class="text-uppercase small font-weight-bold">Total</strong><span>$250</span></li>
                    <li>
                      <form action="#">
                        <div class="input-group mb-0">
                          <input class="form-control" type="text" placeholder="Enter your coupon">
                          <button class="btn btn-dark btn-sm w-100" type="submit"> <i class="fas fa-gift me-2"></i>Apply coupon</button>
                        </div>
                      </form>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>
{% endblock content %}

templates/main/checkout.html
{% extends 'base.html' %} {% load humanize %} {% load static %} 
{% block title %}Welcome to AMYDO-MARKET {% endblock title %} {% block content %}
<div class="container">
  <!-- HERO SECTION-->
  <section class="py-5 bg-light">
    <div class="container">
      <div class="row px-4 px-lg-5 py-lg-4 align-items-center">
        <div class="col-lg-6">
          <h1 class="h2 text-uppercase mb-0">Checkout</h1>
        </div>
        <div class="col-lg-6 text-lg-end">
          <nav aria-label="breadcrumb">
            <ol class="breadcrumb justify-content-lg-end mb-0 px-0 bg-light">
              <li class="breadcrumb-item">
                <a class="text-dark" href="{% url 'amydo:index' %}">Home</a>
              </li>
              <li class="breadcrumb-item">
                <a class="text-dark" href="{% url 'amydo:my-cart' %}">Cart</a>
              </li>
              <li class="breadcrumb-item active" aria-current="page">
                Checkout
              </li>
            </ol>
          </nav>
        </div>
      </div>
    </div>
  </section>
  <section class="py-5">
    <!-- BILLING ADDRESS-->
    <h2 class="h5 text-uppercase mb-4">Billing details</h2>
    <div class="row">
      <div class="col-lg-8">
        <form action="#">
          <div class="row gy-3">
            <div class="col-lg-6">
              <label class="form-label text-sm text-uppercase" for="firstName"
                >First name
              </label>
              <input
                class="form-control form-control-lg"
                type="text"
                id="firstName"
                placeholder="Enter your first name"
              />
            </div>
            <div class="col-lg-6">
              <label class="form-label text-sm text-uppercase" for="lastName"
                >Last name
              </label>
              <input
                class="form-control form-control-lg"
                type="text"
                id="lastName"
                placeholder="Enter your last name"
              />
            </div>
            <div class="col-lg-6">
              <label class="form-label text-sm text-uppercase" for="email"
                >Email address
              </label>
              <input
                class="form-control form-control-lg"
                type="email"
                id="email"
                placeholder="e.g. Jason@example.com"
              />
            </div>
            <div class="col-lg-6">
              <label class="form-label text-sm text-uppercase" for="phone"
                >Phone number
              </label>
              <input
                class="form-control form-control-lg"
                type="tel"
                id="phone"
                placeholder="e.g. +02 245354745"
              />
            </div>
            <div class="col-lg-6">
              <label class="form-label text-sm text-uppercase" for="company"
                >Company name (optional)
              </label>
              <input
                class="form-control form-control-lg"
                type="text"
                id="company"
                placeholder="Your company name"
              />
            </div>
            <div class="col-lg-6 form-group">
              <label class="form-label text-sm text-uppercase" for="country"
                >Country</label
              >
              <br>
              <select
                class="form-control form-control-lg country"
                id="country"
                data-customclass="form-control form-control-lg rounded-0"
              >
                <option value>Choose your country</option>
              </select>
            </div>
            <div class="col-lg-12">
              <label class="form-label text-sm text-uppercase" for="address"
                >Address line 1
              </label>
              <input
                class="form-control form-control-lg"
                type="text"
                id="address"
                placeholder="House number and street name"
              />
            </div>
            <div class="col-lg-12">
              <label class="form-label text-sm text-uppercase" for="addressalt"
                >Address line 2
              </label>
              <input
                class="form-control form-control-lg"
                type="text"
                id="addressalt"
                placeholder="Apartment, Suite, Unit, etc (optional)"
              />
            </div>
            <div class="col-lg-6">
              <label class="form-label text-sm text-uppercase" for="city"
                >Town/City
              </label>
              <input
                class="form-control form-control-lg"
                type="text"
                id="city"
              />
            </div>
            <div class="col-lg-6">
              <label class="form-label text-sm text-uppercase" for="state"
                >State/County
              </label>
              <input
                class="form-control form-control-lg"
                type="text"
                id="state"
              />
            </div>
            <div class="col-lg-6">
              <button
                class="btn btn-link text-dark p-0 shadow-0"
                type="button"
                data-bs-toggle="collapse"
                data-bs-target="#alternateAddress"
              >
                <div class="form-check">
                  <input
                    class="form-check-input"
                    id="alternateAddressCheckbox"
                    type="checkbox"
                  />
                  <label class="form-check-label" for="alternateAddressCheckbox"
                    >Alternate billing address</label
                  >
                </div>
              </button>
            </div>
            <div class="collapse" id="alternateAddress">
              <div class="row gy-3">
                <div class="col-12 mt-4">
                  <h2 class="h4 text-uppercase mb-4">
                    Alternative billing details
                  </h2>
                </div>
                <div class="col-lg-6">
                  <label
                    class="form-label text-sm text-uppercase"
                    for="firstName2"
                    >First name
                  </label>
                  <input
                    class="form-control form-control-lg"
                    type="text"
                    id="firstName2"
                    placeholder="Enter your first name"
                  />
                </div>
                <div class="col-lg-6">
                  <label
                    class="form-label text-sm text-uppercase"
                    for="lastName2"
                    >Last name
                  </label>
                  <input
                    class="form-control form-control-lg"
                    type="text"
                    id="lastName2"
                    placeholder="Enter your last name"
                  />
                </div>
                <div class="col-lg-6">
                  <label class="form-label text-sm text-uppercase" for="email2"
                    >Email address
                  </label>
                  <input
                    class="form-control form-control-lg"
                    type="email"
                    id="email2"
                    placeholder="e.g. Jason@example.com"
                  />
                </div>
                <div class="col-lg-6">
                  <label class="form-label text-sm text-uppercase" for="phone2"
                    >Phone number
                  </label>
                  <input
                    class="form-control form-control-lg"
                    type="tel"
                    id="phone2"
                    placeholder="e.g. +02 245354745"
                  />
                </div>
                <div class="col-lg-6">
                  <label
                    class="form-label text-sm text-uppercase"
                    for="company2"
                    >Company name (optional)
                  </label>
                  <input
                    class="form-control form-control-lg"
                    type="text"
                    id="company2"
                    placeholder="Your company name"
                  />
                </div>
                <div class="col-lg-6 form-group">
                  <label
                    class="form-label text-sm text-uppercase"
                    for="countryAlt"
                    >Country</label
                  >
                    <span></span>
                  <select
                    class="form-control form-control-lg country"
                    id="countryAlt"
                    data-customclass="form-control form-control-lg rounded-0"
                  >
                    <option value>Choose your country</option>
                  </select>
                </div>
                <div class="col-lg-12">
                  <label
                    class="form-label text-sm text-uppercase"
                    for="address2"
                    >Address line 1
                  </label>
                  <input
                    class="form-control form-control-lg"
                    type="text"
                    id="address2"
                    placeholder="House number and street name"
                  />
                </div>
                <div class="col-lg-12">
                  <label
                    class="form-label text-sm text-uppercase"
                    for="addressalt2"
                    >Address line 2
                  </label>
                  <input
                    class="form-control form-control-lg"
                    type="text"
                    id="addressalt2"
                    placeholder="Apartment, Suite, Unit, etc (optional)"
                  />
                </div>
                <div class="col-lg-6">
                  <label class="form-label text-sm text-uppercase" for="city2"
                    >Town/City
                  </label>
                  <input
                    class="form-control form-control-lg"
                    type="text"
                    id="city2"
                  />
                </div>
                <div class="col-lg-6">
                  <label class="form-label text-sm text-uppercase" for="state2"
                    >State/County
                  </label>
                  <input
                    class="form-control form-control-lg"
                    type="text"
                    id="state2"
                  />
                </div>
              </div>
            </div>
            <div class="col-lg-12 form-group">
              <button class="btn btn-dark" type="submit">Place order</button>
            </div>
          </div>
        </form>
      </div>
      <!-- ORDER SUMMARY-->
      <div class="col-lg-4">
        <div class="card border-0 rounded-0 p-lg-4 bg-light">
          <div class="card-body">
            <h5 class="text-uppercase mb-4">Your order</h5>
            <ul class="list-unstyled mb-0">
              <li class="d-flex align-items-center justify-content-between">
                <strong class="small fw-bold">Red digital smartwatch</strong
                ><span class="text-muted small">$250</span>
              </li>
              <li class="border-bottom my-2"></li>
              <li class="d-flex align-items-center justify-content-between">
                <strong class="small fw-bold">Gray Nike running shoes</strong
                ><span class="text-muted small">$351</span>
              </li>
              <li class="border-bottom my-2"></li>
              <li class="d-flex align-items-center justify-content-between">
                <strong class="text-uppercase small fw-bold">Total</strong
                ><span>$601</span>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>
{% endblock content %}

templates/sidebar.html
<!-- SHOP SIDEBAR-->
              <div class="col-lg-3 order-2 order-lg-1">
                <h5 class="text-uppercase mb-4">Categories</h5>
              
  
                  {% for cat in all_category %}
                 <div class="py-2 px-4 bg-dark text-white mb-3"><strong class="small text-uppercase fw-bold">
                  <a href=" {% url 'amydo:category' cat.slug %} ">
                  {{cat.title}}
                  </a>
                </strong></div>
                  {% endfor %}

              </div>